compatibility_date = "2025-09-22"

[build]
command = "npm run build"
watch_dir = "src"

[env.workers]
name = "bpb-worker-panel"
main = "dist/worker.js"

[env.pages]
name = "bpb-pages-panel"
pages_build_output_dir = "dist/pages"
